services:
  - type: web
    name: speech-analyzer
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: python backend/app.py
    autoDeploy: true

    envVars:
      - key: ASSEMBLYAI_API_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: CLERK_SECRET_KEY
        sync: false
      - key: CLERK_PUBLISHABLE_KEY
        sync: false